# SQL Server (2005 or higher recommended)
#
# Install the adapters and driver
#   gem install tiny_tds
#   gem install activerecord-sqlserver-adapter
#
# Ensure the activerecord adapter and db driver gems are defined in your Gemfile
#   gem 'tiny_tds'
#   gem 'activerecord-sqlserver-adapter'
#
# You should make sure freetds is configured correctly first.
# freetds.conf contains host/port/protocol_versions settings.
# http://freetds.schemamania.org/userguide/freetdsconf.htm
#
# A typical Microsoft server
#   [mssql]
#   host = mssqlserver.yourdomain.com
#   port = 1433
#   tds version = 7.1

# If you can connect with "tsql -S servername", your basic FreeTDS installation is working.
# 'man tsql' for more info
# Set timeout to a larger number if valid queries against a live db fail
#
default: &default
  adapter: sqlserver
  encoding: utf8
  reconnect: <%= ENV.fetch('DB_RECONNECT', false)                %>
  username:  <%= ENV.fetch('DB_USERNAME', '')                    %>
  password:  <%= ENV.fetch('DB_PASSWORD', '')                    %>
  host:      <%= ENV.fetch('DB_PORT_5432_TCP_ADDR', 'localhost') %>
  port:      <%= ENV.fetch('DB_PORT_5432_TCP_PORT', '1443')      %>
  timeout: 25


development:
  <<: *default

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: metrofuture_server_test
#
production:
  <<: *default